name: Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: node_module instalation
        run: npm install
      - name: angular cli instalation
        run: npm install -g @angular/cli
      - name: build
        run: ng build
      - run: sudo apt-get install rar
      - name: Adding rar
        run: rar a dist.rar dist
