name: Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.19.0'
      - name: before_script
        run: npm install
        run: npm install -g @angular/cli
      - name: script
        run: ng build
        run: ng build --prod
      - name: after_sucess
